#import <Foundation/Foundation.h>
#import "NGSCreateProjectFeedbackRequest.h"
#import "NGSProblemDetails.h"
#import "NGSProjectFeedbackResponse.h"
#import "NGSApi.h"

/**
* Stardust API
* Stardust is the supporting API for the ProAssist app
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface NGSFeedbackApi: NSObject <NGSApi>

extern NSString* kNGSFeedbackApiErrorDomain;
extern NSInteger kNGSFeedbackApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(NGSApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Creates a job feedback based on event flow and portal.
/// 
///
/// @param applicationName 
/// @param jobFeedbackRequest 
/// @param xClientIdentifier Client Identifier (default to Set Client Identifier)
/// @param xAPIKey Client API Key (default to Set Key)
/// 
///  code:201 message:"",
///  code:400 message:"",
///  code:401 message:"",
///  code:404 message:""
///
/// @return void
-(NSURLSessionTask*) addJobFeedbackWithApplicationName: (NSString*) applicationName
    jobFeedbackRequest: (NGSCreateProjectFeedbackRequest*) jobFeedbackRequest
    xClientIdentifier: (NSString*) xClientIdentifier
    xAPIKey: (NSString*) xAPIKey
    completionHandler: (void (^)(NSError* error)) handler;


/// Gets feedback for a job.
/// 
///
/// @param applicationName The calling application name
/// @param resourceType The resource type, such as job, loss, etc.
/// @param identifier The identifier of the resource
/// @param xClientIdentifier Client Identifier (default to Set Client Identifier)
/// @param xAPIKey Client API Key (default to Set Key)
/// 
///  code:200 message:"A list of feedback from a job",
///  code:400 message:"",
///  code:401 message:"",
///  code:404 message:""
///
/// @return NSArray<NGSProjectFeedbackResponse>*
-(NSURLSessionTask*) getJobFeedbackByResourceWithApplicationName: (NSString*) applicationName
    resourceType: (NSString*) resourceType
    identifier: (NSString*) identifier
    xClientIdentifier: (NSString*) xClientIdentifier
    xAPIKey: (NSString*) xAPIKey
    completionHandler: (void (^)(NSArray<NGSProjectFeedbackResponse>* output, NSError* error)) handler;



@end
