#import <Foundation/Foundation.h>
#import "NGSObject.h"

/**
* Stardust API
* Stardust is the supporting API for the ProAssist app
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "NGSParticipantRequest.h"
@protocol NGSParticipantRequest;
@class NGSParticipantRequest;



@protocol NGSCreateProjectFeedbackRequest
@end

@interface NGSCreateProjectFeedbackRequest : NGSObject


@property(nonatomic) NSString* portalIdentifier;

@property(nonatomic) NSString* eventFlowIdentifier;

@property(nonatomic) NSNumber* rating;

@property(nonatomic) NSString* text;

@property(nonatomic) NGSParticipantRequest* subject;

@property(nonatomic) NGSParticipantRequest* rater;

@end
