#import <Foundation/Foundation.h>
#import "NGSObject.h"

/**
* Stardust API
* Stardust is the supporting API for the ProAssist app
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "NGSAddress.h"
#import "NGSEditParticipantRequest.h"
@protocol NGSAddress;
@class NGSAddress;
@protocol NGSEditParticipantRequest;
@class NGSEditParticipantRequest;



@protocol NGSEditProjectRequest
@end

@interface NGSEditProjectRequest : NGSObject


@property(nonatomic) NSString* identifier;

@property(nonatomic) NSString* projectName;

@property(nonatomic) NSArray<NSString*>* resourcePaths;

@property(nonatomic) NGSAddress* lossAddress;

@property(nonatomic) NGSAddress* officeAddress;

@property(nonatomic) NGSEditParticipantRequest* lossAddressContact;

@property(nonatomic) NGSEditParticipantRequest* initiator;

@property(nonatomic) NGSEditParticipantRequest* technician;

@property(nonatomic) NSArray<NGSEditParticipantRequest>* externalParticipants;

@end
