#import <Foundation/Foundation.h>
#import "NGSObject.h"

/**
* Stardust API
* Stardust is the supporting API for the ProAssist app
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "NGSEventFlowStateResponse.h"
#import "NGSParticipantResponse.h"
@protocol NGSEventFlowStateResponse;
@class NGSEventFlowStateResponse;
@protocol NGSParticipantResponse;
@class NGSParticipantResponse;



@protocol NGSEventFlowResponse
@end

@interface NGSEventFlowResponse : NGSObject


@property(nonatomic) NSString* eventFlowIdentifier;

@property(nonatomic) NSString* currentState;

@property(nonatomic) NGSParticipantResponse* owner;

@property(nonatomic) NGSParticipantResponse* initiator;

@property(nonatomic) NGSParticipantResponse* recipient;

@property(nonatomic) NSDate* dateInitiatedUtc;

@property(nonatomic) NSString* projectIdentifier;

@property(nonatomic) NSDate* dateCompletedUtc;

@property(nonatomic) NSArray<NGSEventFlowStateResponse>* states;

@property(nonatomic) NSString* status;

@property(nonatomic) NSString* portalIdentifier;

@end
