#import <Foundation/Foundation.h>
#import "NGSObject.h"

/**
* Stardust API
* Stardust is the supporting API for the ProAssist app
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "NGSAddressRequest.h"
#import "NGSParticipantRequest.h"
@protocol NGSAddressRequest;
@class NGSAddressRequest;
@protocol NGSParticipantRequest;
@class NGSParticipantRequest;



@protocol NGSEventStateRequest
@end

@interface NGSEventStateRequest : NGSObject


@property(nonatomic) NSString* varNewState;

@property(nonatomic) NGSParticipantRequest* initiator;

@property(nonatomic) NGSParticipantRequest* owner;

@property(nonatomic) NGSParticipantRequest* recipient;

@property(nonatomic) NSString* notes;

@property(nonatomic) NGSAddressRequest* lossAddress;

@property(nonatomic) NGSAddressRequest* officeAddress;

@property(nonatomic) NSDate* estimatedCompletionDateUtc;

@property(nonatomic) NSDate* startDateUtc;

@property(nonatomic) NSString* companyName;

@property(nonatomic) NSString* emailAddress;

@property(nonatomic) NSString* webReviewUri;

@property(nonatomic) NSString* websiteUri;

@property(nonatomic) NSArray<NSString*>* resourcePaths;

@property(nonatomic) NSArray<NGSParticipantRequest>* externalParticipants;

@end
