#import <Foundation/Foundation.h>
#import "NGSObject.h"

/**
* Stardust API
* Stardust is the supporting API for the ProAssist app
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "NGSInviteParticipantResponse.h"
@protocol NGSInviteParticipantResponse;
@class NGSInviteParticipantResponse;



@protocol NGSInviteResponse
@end

@interface NGSInviteResponse : NGSObject


@property(nonatomic) NSString* inviteIdentifier;

@property(nonatomic) NSArray<NSString*>* resourcePaths;

@property(nonatomic) NSString* portalIdentifier;

@property(nonatomic) NSString* projectIdentifier;

@property(nonatomic) NSArray<NGSInviteParticipantResponse>* recipients;

@property(nonatomic) NSDate* dateCreatedUtc;

@property(nonatomic) NSDate* dateUpdatedUtc;

@end
