#import <Foundation/Foundation.h>
#import "NGSObject.h"

/**
* Stardust API
* Stardust is the supporting API for the ProAssist app
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "NGSEntityBase.h"
#import "NGSProject.h"
#import "NGSStatus.h"
@protocol NGSEntityBase;
@class NGSEntityBase;
@protocol NGSProject;
@class NGSProject;
@protocol NGSStatus;
@class NGSStatus;



@protocol NGSProjectGroup
@end

@interface NGSProjectGroup : NGSEntityBase


@property(nonatomic) NSString* projectGroupName;

@property(nonatomic) NSString* clientIdentifier;

@property(nonatomic) NGSStatus* status;

@property(nonatomic) NSArray<NGSProject>* projects;

@end
