#import <Foundation/Foundation.h>
#import "NGSObject.h"

/**
* Stardust API
* Stardust is the supporting API for the ProAssist app
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "NGSParticipantResponse.h"
@protocol NGSParticipantResponse;
@class NGSParticipantResponse;



@protocol NGSProjectFeedbackResponse
@end

@interface NGSProjectFeedbackResponse : NGSObject


@property(nonatomic) NSString* projectFeedbackIdentifier;

@property(nonatomic) NSString* eventFlowIdentifier;

@property(nonatomic) NSNumber* rating;

@property(nonatomic) NSString* feedbackText;

@property(nonatomic) NSString* portalIdentifier;

@property(nonatomic) NGSParticipantResponse* subject;

@property(nonatomic) NGSParticipantResponse* rater;

@property(nonatomic) NSDate* dateCreatedUtc;

@property(nonatomic) NSDate* dateUpdatedUtc;

@property(nonatomic) NSDate* dateAppointmentStartUtc;

@property(nonatomic) NSDate* dateAppointmentCompleteUtc;

@end
