#import <Foundation/Foundation.h>
#import "NGSObject.h"

/**
* Stardust API
* Stardust is the supporting API for the ProAssist app
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol NGSParticipantRequest
@end

@interface NGSParticipantRequest : NGSObject


@property(nonatomic) NSString* firstName;

@property(nonatomic) NSString* lastName;

@property(nonatomic) NSString* mobilePhoneNumber;

@property(nonatomic) NSString* emailAddress;

@property(nonatomic) NSString* companyName;

@property(nonatomic) NSString* imageUri;

@property(nonatomic) NSArray<NSString*>* resourcePaths;

@property(nonatomic) NSArray<NSString*>* tags;

@end
