#import <Foundation/Foundation.h>
#import "NGSObject.h"

/**
* Stardust API
* Stardust is the supporting API for the ProAssist app
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "NGSCommunicationPreference.h"
#import "NGSEntityBase.h"
#import "NGSParticipantType.h"
@protocol NGSCommunicationPreference;
@class NGSCommunicationPreference;
@protocol NGSEntityBase;
@class NGSEntityBase;
@protocol NGSParticipantType;
@class NGSParticipantType;



@protocol NGSParticipant
@end

@interface NGSParticipant : NGSEntityBase


@property(nonatomic) NSString* firstName;

@property(nonatomic) NSString* lastName;

@property(nonatomic) NSString* mobilePhoneNumber;

@property(nonatomic) NSString* emailAddress;

@property(nonatomic) NSString* companyName;

@property(nonatomic) NGSCommunicationPreference* communicationPreference;

@property(nonatomic) NSString* imageUri;

@property(nonatomic) NGSParticipantType* participantType;

@property(nonatomic) NSArray<NSString*>* resourcePaths;

@property(nonatomic) NSArray<NSString*>* tags;

@property(nonatomic) NSString* hashLookup;

@end
