#import <Foundation/Foundation.h>
#import "NGSObject.h"

/**
* Stardust API
* Stardust is the supporting API for the ProAssist app
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "NGSAddress.h"
#import "NGSEntityBase.h"
#import "NGSParticipant.h"
@protocol NGSAddress;
@class NGSAddress;
@protocol NGSEntityBase;
@class NGSEntityBase;
@protocol NGSParticipant;
@class NGSParticipant;



@protocol NGSProject
@end

@interface NGSProject : NGSEntityBase


@property(nonatomic) NSString* projectGroupIdentifier;

@property(nonatomic) NSArray<NSString*>* resourcePaths;

@property(nonatomic) NSString* projectName;

@property(nonatomic) NGSAddress* lossAddress;

@property(nonatomic) NGSAddress* officeAddress;

@property(nonatomic) NSArray<NGSParticipant>* participants;

@property(nonatomic) NSDate* startDateUtc;

@property(nonatomic) NSDate* estimatedCompletionDateUtc;

@property(nonatomic) NSString* companyName;

@property(nonatomic) NSString* emailAddress;

@property(nonatomic) NSString* webReviewUri;

@property(nonatomic) NSString* websiteUri;

@property(nonatomic) NSString* hashLookup;

@end
